#!/usr/bin/env bash
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#                                                           #
#  888888 8888888              88 8888888                   #
#    88   88                   88 88    oo                  #
#    88   88                   88 88                        #
#    88   88888 .d8b.   .d8b.  88 88888 88 8888b.  .d8b.    #
#    88   88   d8P Y8b d8P Y8b 88 88    88 88  8b d8P Y8b   #
#    88   88   8888888 8888888 88 88    88 88  88 8888888   #
#    88   88   Y8b.    Y8b.    88 88    88 88  88 Y8b.      #
#  888888 88    ºY888P  ºY888P 88 88    88 88  88  ºY888P   #
#                           (c) 2015-2024 I Feel Fine, Inc. #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# ghost-init
# Github Repo: <ifeelfine/ghost-init>
# -------------
# Description: 
# Initializes the ghost directories and installs the s3
# storage plugin, if needed. Updates configMap variables to
# values from the 1Password secret.
# -------------
# Version 0.4.0 (see GH repo for release notes)

set -e # Exit on error

# Variable Declaration
# ====================
COMMANDS_MISSING=()                                     # Missing command list
COMMANDS="envsubst curl jq"                             # Linux commands needed for proper execution
CONFIG_FILE="/var/lib/ghost/config.production.json"     # Name of Ghost config file
CONFIG_TEMP="./${CONFIG_FILE##*/}.tmp"
DEBUG=${DEBUG:-false}                                   # Assume debug is off unless specifically set
GHOST_CONTENT=${GHOST_CONTENT:-/var/lib/ghost/content}  # Set Ghost content directory
STORAGE_PROVIDER=${STORAGE_PROVIDER:-}                  # Storage provider
SUB_CREATED=false                                       # Indicates a subdirectory was created
SUB_DIRS="apps data files images logs media public settings themes" # Directories within $GHOST_CONTENT

# Print Functions
# ===============
_echo() {
  /bin/echo -e "$(date +%Y-%m-%dT%H:%M:%S.%3N-%Z) $*"
}
_ok() {
  _echo "[ \033[0;32mOK\033[0m    ] $*"
}
_warn() {
  _echo "[ \033[1;33mWARN\033[0m  ] \033[1;33m$*"
}
_error() {
  _echo "[ \033[0;31mERROR\033[0m ] $*"
}
_debug() {
  $DEBUG && _echo "[ \033[0;38;5;40mDEBUG\033[0m ] $*"
}

# Preamble
# ========
# Check to make sure that the required tools have been installed with the Dockerfile

for cmd in $COMMANDS; do
  if command -v $cmd >/dev/null; then
    _debug "\033[0;34m$cmd\033[0m is installed and available for use"
  else
    _debug "\033[0;34m$cmd\033[0m is required but not installed."
    COMMANDS_MISSING+=("$cmd")
  fi
done

if [ ${#COMMANDS_MISSING[@]} -gt 0 ]; then
  _error "The following required commands are missing:"
  printf '%s [ \033[0;31mERROR\033[0m ]   - \033[0;34m%s\033[0m\n' "$(date +%Y-%m-%dT%H:%M:%S-%Z)" "${COMMANDS_MISSING[@]}"
  _echo
  _error "Init script \033[0;31mfailed\033[0m to complete."
  exit 2
fi

if [[ "${GHOST_CONTENT}" != /* ]]; then
  _error "\033[0;34mGHOST_CONTENT\033[0m must be an \033[0;31mabsolute path\033[0m, but you provided \"${GHOST_CONTENT}\"."
  _echo
  _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1;
fi


# Main Content
# ============
_ok "\033[0;32m;Ghost init script started...\033[0m"
_echo
_debug "\$\033[0;35mGHOST_CONTENT\033[0m = \033[0;34m$GHOST_CONTENT\033[0m"
_debug "\$\033[0;35mUSR_GRP\033[0m       = \033[0;34m$USR_GRP\033[0m"
_debug "\$\033[0;35mCONFIG_FILE\033[0m   = \033[0;34m$CONFIG_FILE\033[0m"

# Step 1. Check if the content directory exists and if not create it
_echo "1. Checking if \033[0;34m${GHOST_CONTENT}\033[0m exists."

if [[ ! -d "${GHOST_CONTENT}" ]]; then
  _debug "\033[0;34m${GHOST_CONTENT}\033[0m doesn't exist. Creating it."
  if mkdir -p "${GHOST_CONTENT}"; then
    _ok "\033[0;34m${GHOST_CONTENT}\033[0m directory \033[0;38;5;40mcreated\033[0m."
  else
    _error "\033[0;31mfailed\033[0m to create \033[0;34m${GHOST_CONTENT}\033[0m. Exiting..."
    _error
    _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
  fi
else
  _ok "\033[0;34m${GHOST_CONTENT}\033[0m already exists."
fi
_echo

# Step 2. Ensure the sub directories of ${GHOST_CONTENT} exist.
_echo "2. Checking for subdirectories of \033[0;34m${GHOST_CONTENT}\033[0m."

_debug "Attempting to create subdirectories \033[0;35m${SUB_DIRS// /, }\033[0m..."
for DIR in $SUB_DIRS; do
  _debug "Checking if \033[0;34m${GHOST_CONTENT}\033[0m/\033[0;35m${DIR}\033[0m exists."
  if [[ ! -d "${GHOST_CONTENT}/${DIR}" ]]; then 
    if mkdir -p "${GHOST_CONTENT}/${DIR}"; then
      _debug "\"${GHOST_CONTENT}/${DIR}\ created"
      SUB_CREATED=true
    else 
    _error "\033[0;31mfailed\033[0m to create \033[0;34m${GHOST_CONTENT}\033[0m/\033[0;35m${DIR}\033[0m. Exiting..."
    _error
    _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
    fi
  else _debug "\033[0;34m${GHOST_CONTENT}\033[0m/\033[0;35m${DIR}\033[0m already exists."
  fi
done

if $SUB_CREATED; then
  _ok "Finished creating subdirectories of \033[0;34m${GHOST_CONTENT}\033[0m."
else
  _ok "All subdirectories of \033[0;34m${GHOST_CONTENT}\033[0m already exist."
fi
_echo

# Step 3. Install storage adapter, if required
_echo "3. Checking for a storage adapter and installing the plugin, if required."
_debug "\$\033[0;35mSTORAGE_PROVIDER\033[0m = \033[0;34m${STORAGE_PROVIDER}\033[0m"

case "${STORAGE_PROVIDER,,}" in
  "s3")
    _ok "Using S3 for storage"
    _echo "3.1 Installing the \033[0;38;5;40mghos3\033[0m plug-in"
    _debug "Set working directory to /opt/node"
    cd /opt/node
    _debug "Running npm install \033[0;38;5;40mghos3\033[0m."
    if npm install ghos3; then
      _ok "Installed \033[0;38;5;40mghos3\033[0m plug-in"
      if mkdir -p "${GHOST_CONTENT}/adapters/storage" && mv node_modules/ghos3 "${GHOST_CONTENT}/adapters/storage/s3"; then
        _debug "Moved \033[0;38;5;40mghos3\033[0m plug-in to \033[0;34m${GHOST_CONTENT}/adapters/storage/s3\033[0m"
      else
        _error "\033[0;31mfailed\033[0m to copy \033[0;38;5;40mghos3\033[0m plug-in to \"${GHOST_CONTENT}/adapters/storage/s3\". Exiting..."
        _echo
        _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
      fi
    else
      _error "\033[0;31mfailed\033[0m to install \033[0;38;5;40mghos3\033[0m plug-in. Exiting..." 
      _echo
      _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
    fi
    ;;
  "")
    _warn "Storage driver not specified. Is this correct?"
    ;;
  *)
    _ok "Using local storage"
    _debug "No action required."
    ;;
esac

# Step 4. Perform ConfigMap variable substitution
_echo "4. Processing ConfigMap against environment variables."

_debug "Looking for config file at \033[0;34m${CONFIG_FILE}\033[0m"
if [[ -f "$CONFIG_FILE" ]]; then
  cd /opt/node
  _debug "Found config file at \033[0;34m${CONFIG_FILE}\033[0m."
      # Replace environment variables in the config file
  # This will replace any ${VARIABLE} or $VARIABLE with its value
  if envsubst < "$CONFIG_FILE" > "$CONFIG_TEMP"; then                         #####  && mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
    _debug "Variable substitution in \033[0;34m${CONFIG_TEMP}\033[0m successful."
    if jq empty "${CONFIG_FILE}" 2>/dev/null; then
      if mv ."$CONFIG_TEMP" "$CONFIG_FILE"; then
        :
      else
        _error "\033[0;31mFailed\033[0m to properly overwrite \033[0;34m${CONFIG_FILE}\033[0m with the temporary file. Exiting..."
        _echo
        _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
      fi
      _ok "Substitutions completed successfully. File is structurally correct."
    else
      _warn "Substitution completed successfully, but file is not structurally correct."
      _warn "Review environment variables to ensure they are stored correctly and try again."
      _echo
      _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
    fi
    _debug "Updated configMap file:"
    _debug "$(cat ${CONFIG_FILE})"
  else
    _error "\033[0;31mfailed\033[0m to substitute environment variables in config file. Exiting..."
    _echo
    _error "Init script \033[0;31mfailed\033[0m to complete." && exit 1
  fi
else
  _warn "Config file ${CONFIG_FILE##*/} not found in directory ${CONFIG_FILE%/*}/"
  _warn "Ghost may not function correctly."
  _warn "Review your manifest to ensure it is correct and properly references config variables."
  _warn "Init script \033[0;31mfailed\033[0m to complete." && exit 78

fi

_ok "Init script completed successfully."
exit 0